# Generated by Django 4.2.20 on 2025-04-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_address_id_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedesign',
            name='styled_templates',
            field=models.JSONField(default=dict),
        ),
    ]
