# Generated by Django 4.2.20 on 2025-04-10 16:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_completedesign_styled_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
