# Generated by Django 4.2.20 on 2025-04-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_styles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='styles',
            name='image_url',
            field=models.URLField(default='https://res.cloudinary.com/djfgkkrts/image/upload/v1744303018/the-shipwreck-of-the-minotaur.jpg'),
        ),
    ]
