# Generated by Django 4.2.20 on 2025-04-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_styles_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styles',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='styles',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
